[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'kontrol-cheatcodes=lib/kontrol-cheatcodes/src',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[fuzz]
runs = 1000
seed = '0x71'

[invariant]
runs = 64
depth = 32
fail_on_revert = true
